name: Validation

on:
    workflow_dispatch:
    pull_request:
    push:
        paths:
            - "domains/*"
            - ".github/workflows/validation.yml"
            - "scripts/*"

concurrency:
    group: ${{ github.ref }}-validation
    cancel-in-progress: true

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check
              uses: koenrh/dnscontrol-action@v3
              with:
                  args: check
                  config_file: "scripts/dnsconfig.js"
    json:
        name: JSON
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: JSON Syntax Check
              uses: limitusus/json-syntax-check@v2
              with:
                  pattern: "\\.json$"
              env:
                  BASE: "domains/"
            - name: Validate JSON Schema
              uses: cardinalby/schema-validator-action@v3
              with:
                file: 'domains/*.json'
                schema: 'scripts/schema.json'
